CREATE TABLE IF NOT EXISTS ORDER_BOOK (
    Order_ID INT,
    Book_ID INT,
    PRIMARY KEY (Order_ID, Book_ID),
    FOREIGN KEY (Order_ID) REFERENCES `ORDER`(Order_ID),
    FOREIGN KEY (Book_ID) REFERENCES BOOK(Book_ID)
);
